#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$application = new Symfony\Component\Console\Application();

$application->add(new LorinLee\LaradockCli\Console\InitCommand);
$application->add(new LorinLee\LaradockCli\Console\UpCommand);
$application->add(new LorinLee\LaradockCli\Console\WorkspaceCommand);
$application->add(new LorinLee\LaradockCli\Console\StopCommand);

$application->run();